name: nadym
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  firebase_storage: 3.1.6
  firebase_dynamic_links: 0.5.1
  firebase_analytics: 5.0.16
  firebase_database: ^3.1.6


  cupertino_icons: ^0.1.3
  google_fonts: ^1.1.0
  provider: ^4.3.0
  flutter_bloc: '>2.1.1 <=3.0.0'

  cloud_firestore: ^0.13.7
  fluttertoast: ^3.1.3
  curved_navigation_bar: ^0.3.3

#  пакеты для новостей
  cached_network_image:
  equatable:
  http: ^0.12.2
  webview_flutter: ^0.3.22+1

#  проверяем как щас будет работать
  flutter_cache_manager: ^1.4.1


  extended_image: ^0.7.3+1
  like_button: 1.0.1
  loading_more_list: 3.0.0
  http_client_helper: ^0.2.1
  json_annotation: 3.0.1
  image_cropper: 1.1.1
  image_picker: ^0.6.7
  uuid: ^2.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  enum_to_string: 1.0.8
  graphql_flutter: 3.0.0

  carousel_slider: 1.4.0
  sliding_up_panel: 0.3.6
  auto_orientation: 1.0.6
  font_awesome_flutter: 8.5.0

  flutter_markdown: 0.3.2
  flutter_typeahead: 1.8.3
  recursive_regex: 0.1.3+2

  characters: 1.0.0

  flutter_local_notifications: 1.4.4+2
  rxdart: 0.23.1
  package_info: 0.4.1
  email_validator: 1.0.0
  collection: 1.14.12
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - images/fon/
    - images/photo/
    - images/friends/
  #   - images/a_dot_ham.jpeg
  # the asset derictory images/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
